### ISSUE TITLE
simpler than gulp-runtime

### ISSUE THREAD

**Issue by stringparser** [stringparser/gulp-repl#1]
This is maybe what I should have done from the beginning with [gulp-runtime](https://github.com/stringparser/gulp-runtime) just a simple module. 

I think you'll be interested in this one @DarkPark

**Comment by DarkPark** [comment]
thanks
will sure take a look
I also have an alternative point of view on the matter
after I think it over I'm going to discuss it with you - you may like it as well :)

**Comment by stringparser** [comment]
Great :+1:

**Comment by stringparser** [comment]
Know what I just made you collaborator, so do as you see fit ;)

**Comment by DarkPark** [comment]
thanks :)

**Comment by DarkPark** [comment]
it works :)

only one minor thing I've noticed - need to press Ctrl+C twice to exit
the package `node-static` is seems the cause (without this task works fine)
but I remember you've already fixed the similar issue
maybe you can advise something?

**Comment by DarkPark** [comment]
found it:

``` js
var repl = require('gulp-repl');

repl.on('SIGINT', function () {
    process.exit();
});
```

**Comment by stringparser** [comment]
Yep, that's it :). If you want to PR and merge it go ahead. Add an exit code though (`process.exit(0)`). 

I've thought to add the ability to run in a task in series/parallel directly from the repl. But not much more aside of whats here. Any ideas?

**Comment by DarkPark** [comment]
but it's possible to run tasks in parallel
in console I can type:

```
> img jade less
```

and I see in logs that they run in parallel

sadly it's impossible to run a task with options

**Comment by stringparser** [comment]
Yes, gulp runs them in parallel by default. I was talking about this

```
> series img jade less
```

Being `series` a special word for the repl. 

With gulp-runtime you can pass options :).

``` js
var gulp = require('gulp-runtime').create({repl: true});

gulp.task('jade :glob', function(){
  // do stuff
});

gulp.stack('jade app/**/*.jade')();
```

Same using the repl 

```
> jade app/**/*.jade
```

But to do that you have to monkeypatch `gulp.task` so you can modify how tasks are defined. I would like to keep things simple for this one. 

That said, if you find some simple way I'm up to it. 

EDIT: that's one of the reasons I had to do all using vinyl-fs directly

**Comment by DarkPark** [comment]
I see
One more idea - persistent history
using console a log I get used to have a full history of your commands
and in the repl you have it as well but only for the current session
would be cool to save it in a configured file on exit and restore it on start

**Comment by stringparser** [comment]
Yeah, that would be great. They did this on nodejs/io.js#1513, I'll take a look on how they did it. In any case it should be behind an option like `repl({historyFile: 'some/path/here'})` so it does not surprise anyone when it writes to disk.

**Comment by DarkPark** [comment]
agree
seems promising

**Comment by DarkPark** [comment]
one more idea
in case you mistype a task name you get:

```
[16:53:23] Task 'll' is not in your gulpfile
[16:53:23] Please check the documentation for proper gulpfile formatting
```

and process exits
would be nice to not halt the programm

**Comment by stringparser** [comment]
Yep, that's doable. It would be just to check each of the given arguments before running them and see if there is any that is not defined as a task.

**Comment by stringparser** [comment]
What about not exiting the process at all? I mean, just to mistype a name is not a big deal

**Comment by DarkPark** [comment]
I agree
exit should be only explicitly by Ctrl+C

**Comment by stringparser** [comment]
Exit on first `SIGINT`and warning when tasks is not found done in #2 and #3. History thing pending.

**Comment by DarkPark** [comment]
works fine :+1:

**Comment by DarkPark** [comment]
I've mentioned an interesting idea earlier
it's moderately connected with repl
would do you like to discuss it?

**Comment by stringparser** [comment]
Do a PR, I wouldn't mind at all :)

**Comment by DarkPark** [comment]
it would be a new separated project as the work process will differ

**Comment by DarkPark** [comment]
you can say it's an alternative approach
I'm talking about web interface to gulp tasks - to see the list of all tasks, run them, see logs, filter each task log or all tasks at once and so on ...

**Comment by stringparser** [comment]
That would be really cool! 

We could do a native app using [electron](https://github.com/atom/electron) for example.

**Comment by stringparser** [comment]
There is one https://github.com/sindresorhus/gulp-app already :)

**Comment by stringparser** [comment]
But you are talking more like a dashboard and the latter is more like a notifier app, which is also good. I like the idea of a simple app for this.

**Comment by DarkPark** [comment]
will check your links now
but anyway it would be good probably to discuss it somewhere else

**Comment by stringparser** [comment]
ok, other repo right?

**Comment by DarkPark** [comment]
I think maybe skype or email

**Comment by stringparser** [comment]
ok, whatever you like

**Comment by DarkPark** [comment]
my skype - darkpark.infomir
will remove this message as soon as you contact me

**Comment by DarkPark** [comment]
hello
what do you think about ability to set process environment via repl?
e.g.

```
> DEBUG_LEVEL=2 mytask
```

with or without a task

**Comment by stringparser** [comment]
You could do that with `gulp-runtime` like this

``` js
var gulp = require('gulp-runtime').create({repl: true});
gulp.task(':envFlag([A-Z_]+=?\\S*)', function(next){
   console.log(this.params);
   var flag = this.params.envFlag.split('=');
   process.env[flag[0]] = flag[1] || true;
   next();
});

// will run the handle above
gulp.stack('DEBUG_LEVEL=2')();
```

EDIT: I edited so the example is more complete

**Comment by stringparser** [comment]
But maybe is a good idea to put it here anyway it would not take much.

**Comment by DarkPark** [comment]
ok, I'll check it

**Comment by simonfan** [comment]
Thank you so much for the module, haha it's great

**Comment by stringparser** [comment]
:smile: welcome man thanks for the kind words
